"""added new role field

Revision ID: 656256ed4b4f
Revises: 9094aae3c127
Create Date: 2021-12-20 12:03:13.142906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656256ed4b4f'
down_revision = '9094aae3c127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    # ### end Alembic commands ###
