"""added tiago mod

Revision ID: e56f958500f8
Revises: e29fec9ceb1a
Create Date: 2021-12-22 21:35:18.950198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56f958500f8'
down_revision = 'e29fec9ceb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_index('ix_blog_post_date', table_name='blog_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blog_post_date', 'blog_post', ['date'], unique=False)
    op.drop_column('blog_post', 'username')
    # ### end Alembic commands ###
