"""updated role field

Revision ID: e87a60f0d666
Revises: 656256ed4b4f
Create Date: 2021-12-20 12:07:14.994943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87a60f0d666'
down_revision = '656256ed4b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    # ### end Alembic commands ###
